### ISSUE TITLE
AGIPD500K does not have the channel numbers shown in `inspect()`

### ISSUE THREAD

**Issue by daniloefl** [European-XFEL/EXtra-geom#223]

**Comment by tmichela** [comment]
I think none of the detector show the channel number in `.inspect()` (e.g. see AGIPD1M https://extra-geom.readthedocs.io/en/latest/agipd_geometry.html) is this something useful?

**Comment by tmichela** [comment]
FYI, the channel mapping is:

| module | channel |
| --- | --- |
| Q1M1 | 0 |
| Q1M2 | 1 |
| Q1M3 | 2 |
| Q1M4 | 3 |
| Q2M1 | 4 |
| Q2M2 | 5 |
| Q2M3 | 6 |
| Q2M4 | 7 |

**Comment by daniloefl** [comment]
I was thinking of something like this: https://extra-geom.readthedocs.io/en/latest/geometry.html#agipd-1m

Sorry, I thought inspect produced it. If not, can it be produced somehow? This is useful to know what channel goes where looking at the data.

**Comment by tmichela** [comment]
Probably @takluyver produced these images, may still have the code to generate them? (we could also add it to the inspect output, that's probably easy enough).

**Comment by takluyver** [comment]
That AGIPD-1M diagram was made by hand in Inkscape. You can find the SVG source in this repo:

https://github.com/European-XFEL/EXtra-geom/tree/master/docs/_static

The goal with `.inspect()` is just to show whatever naming scheme is most likely to be readily understood. If no-one's calling them Q1M1 etc., let's change that. Poking around the HED Karabo GUI, it looks like `M0` to `M7` would work.

**Comment by daniloefl** [comment]
In my particular case, I would be interested in understanding which data goes where, when the detector is assembled. My data is labelled by a numeric array, so I do think it would be relevant to show which module of the detector would correspond to which data index.

But perhaps this is a niche use case. In any case, if you think it is not a big deal, feel free to close the ticket.
