### ISSUE TITLE
Mini-half modules are flipped in geometry

### ISSUE THREAD

**Issue by cydanil** [European-XFEL/EXtra-geom#40]
Within the calibration team, we use extra-geom 1.0.0 for rendering figures in reports.
This works well, but the mini-half geometries have their x-axis reversed.

![image](https://user-images.githubusercontent.com/2159577/101913141-ea910980-3bc2-11eb-82c3-9594bc392c94.png)

This is not that left-right halves are swapped, though.

Currently, we work around the issue by doing a `np.fliplr(data)` prior to creating the figure.  
Here's the same data:

![image](https://user-images.githubusercontent.com/2159577/101913428-4491cf00-3bc3-11eb-8acd-c7120523b51e.png)

I'm happy to make a PR fixing this, with a bit of guidance.

Thanks!

**Comment by takluyver** [comment]
@tmichela, can you have a look? The question foremost in my mind is: do we just have the default geometry wrong in all cases, or is it somehow right for some datasets and wrong for others?

**Comment by cydanil** [comment]
I tried on a number of datasets, and it's the same.  

Having previously talked to Thomas, it seems that the specs provided for implementing the `AGIPD_500K2GGeometry` were incorrect: the x axis was inverted (ie. looking upstream at the beam).

**Comment by takluyver** [comment]
Thanks! So long as we're confident that this is consistently wrong, go ahead and make a PR - I'm happy to try to help if you have questions, or we'll rope Thomas in if I can't. I think this is the relevant piece of code:

https://github.com/European-XFEL/EXtra-geom/blob/18cd04596812d0390689b3a32fc6ec3a6f466655/extra_geom/detectors.py#L1021-L1043

**Comment by tmichela** [comment]
I suppose something like this should work:

```python
        for p in range(cls.n_modules):
            ...

            for a in range(cls.n_tiles_per_module, 0, -1):
                ...

                tiles.append(GeometryFragment(
                    ...
                    ss_vec=np.array([-1, 0, 0]) * unit,
                    ...
                ))
```

**Comment by takluyver** [comment]
We probably need to adjust the corner positions (position of the first pixel in each tile) as well, to keep it in the right place.

For future readability, I'd prefer to have it loop through tiles 0-7 rather than 7-0, unless going backwards otherwise makes the code clearer.

**Comment by tmichela** [comment]
Right, the x origin of each module would now be on the left hand side:

```python
        ref = (0, - (3 * (cls.frag_fs_pixels + panel_gap[1]) * unit))  
        ref = (- (origin[0] * unit + ref[0]), - (origin[1] * unit + ref[1]))  # origin

        modules = []
        for p in range(cls.n_modules):
            panel_corner_y = ref[1] - ((p // 2) * (module_height + panel_gap_y))
            panel_corner_x = ref[0] + ((p % 2 + 1) * (module_width + panel_gap_x))

            tiles = []
            modules.append(tiles)

            for a in range(cls.n_tiles_per_module):
                corner_x = panel_corner_x + a * tile_width

                tiles.append(GeometryFragment(
                    corner_pos=np.array([corner_x, panel_corner_y, 0.]),
                    ss_vec=np.array([-1, 0, 0]) * unit,
                    fs_vec=np.array([0, 1, 0]) * unit,
                    ss_pixels=cls.frag_ss_pixels,
                    fs_pixels=cls.frag_fs_pixels,
                ))
```

![Screenshot from 2020-12-11 16-33-18](https://user-images.githubusercontent.com/32831491/101922963-15815a80-3bcf-11eb-98d4-2e4c26a8ceff.png)

**Comment by takluyver** [comment]
Nice. I take it you'll make a PR for that?

**Comment by tmichela** [comment]
Sure, I'll do that on Monday, unless @cydanil still want to have a go at it. It still probably require some work to adapt the tests and make sure the centre is correct

**Comment by cydanil** [comment]
Thanks for giving me the opportunity! I won't be able to tackle this issue until next week.  
Unless it can wait until next year, then please go ahead :)
