### ISSUE TITLE
'coffset' in the `corner_pos`

### ISSUE THREAD

**Issue by JunCEEE** [European-XFEL/EXtra-geom#59]
https://github.com/European-XFEL/EXtra-geom/blob/c038f9cf88f6fca0055b35f59b681f4c173af7e6/extra_geom/detectors.py#L35

According to https://www.desy.de/~twhite/crystfel/manual-crystfel_geometry.html, `coffset` is already in metres, do we still need to multiply `1/res` to it?

**Comment by takluyver** [comment]
Yes, I think you're right. I think we've worked with geometry files where coffset is usually 0, so we didn't spot this. Do you want to make a PR to fix it?

**Comment by JunCEEE** [comment]
Yes, just did the PR #60
