### ISSUE TITLE
JUNGFRAUGeometry.from_crystfel_geom error

### ISSUE THREAD

**Issue by JunCEEE** [European-XFEL/EXtra-geom#66]
Hello,

I tried to load this crstFEL geometry though `JUNGFRAUGeometry.from_crystfel_geom()` in EXtra-geom-1.2.0, but got this error.

![image](https://user-images.githubusercontent.com/3163505/115032014-1e5da200-9ec9-11eb-8cf9-8c4e0549d529.png)

> clen = 0.1022
> photon_energy = 12800
> 
> adu_per_photon = 1
> res = 13333.3   ; 75 micron pixel size
> 
> ; Uncomment these lines for multi-event file
> dim0 = %
> dim1 = ss
> dim2 = fs
> data = /entry/data/data
> 
> ; Uncomment this line for single-event test file
> ;data = /data/data
> 
> ; Mask out strips between panels
> bad_v0/min_fs = 1030
> bad_v0/min_ss = 0
> bad_v0/max_fs = 1039
> bad_v0/max_ss = 2166
> 
> bad_h0/min_fs = 0
> bad_h0/min_ss = 514
> bad_h0/max_fs = 2069
> bad_h0/max_ss = 550
> 
> bad_h1/min_fs = 0
> bad_h1/min_ss = 1065
> bad_h1/max_fs = 2069
> bad_h1/max_ss = 1101
> 
> bad_h2/min_fs = 0
> bad_h2/min_ss = 1616
> bad_h2/max_fs = 2069
> bad_h2/max_ss = 1652
> 
> panel0/min_fs = 0
> panel0/min_ss = 0
> panel0/max_fs = 2069
> panel0/max_ss = 2166
> panel0/corner_x = -1022.0
> panel0/corner_y = -1084.0
> panel0/fs = x
> panel0/ss = y

**Comment by takluyver** [comment]
Hi Jun,

The `JUNGFRAUGeometry` class expects to get a description of JUNGFRAU's tiles of 256 x 256 pixels, arranged into modules (2 x 4 tiles). It expects each tile to be a separate panel in CrystFEL, rather than one big panel with 'bad' regions marking the gaps.

Perhaps it's easier to start by making the geometry in EXtra-geom, and then save that to a `.geom` file with the expected layout? Have a look at [the JUNGFRAU example notebook](https://extra-geom.readthedocs.io/en/latest/jungfrau_geometry.html). Maybe we could even add support in Simex for using a geometry object from EXtra-geom to define detector layout.

**Comment by JunCEEE** [comment]
Thanks, @takluyver. I've generated the Jungfrau detector geometry as you suggested. I'll ask Andy whether that geometry is in accord with that in ESRF. The problem for me is that the data shape of the simlated data is 512*1024, but the expected data shape should is 8*512*1024. I'm asking T. White about that.

Many thanks,
Jun

**Comment by JunCEEE** [comment]
I've defined a simple geometry class based on the detectorBase class of EXtra-geom:
https://github.com/PaNOSC-ViNYL/SimEx-Lite/blob/692ec35b479b7c9eff14c96b0329316b6c760df1/SimExLite/DiffractionData.py#L544

It would be great if you can give some comments on that!

**Comment by takluyver** [comment]
> The problem for me is that the data shape of the simlated data is 512*1024, but the expected data shape should is 8*512*1024

That sounds like you're simulating just one JUNGFRAU module. JUNGFRAU-4M is made of 8 modules, each 512 * 1024.

> I've defined a simple geometry class based on the detectorBase class of EXtra-geom:

Great! Comments:

- DetectorGeometryBase is not really a public API (it's [not in the docs](https://extra-geom.readthedocs.io/en/latest/geometry.html)). It's fine to do something like this for your own use, but a subclass that works with EXtra-geom 1.2 could stop working with 1.3, or 1.4, or any future version. If you want a reliable interface, we'll need to put something like this in EXtra-geom itself.
- It would be good to describe it more precisely in the docstring: what makes it 'simple'? Specfically, it's one tile on one module, i.e. the detector is one continuous array of pixels.
- For some things,  you may also need to implement the `split_tiles()` and `_module_coords_to_tile()` methods (both of which should be very simple for this case).
