### ISSUE TITLE
Support quadrant positions in h5 files

### ISSUE THREAD

**Issue by FilipeMaia** [European-XFEL/EXtra-geom#91]
It would be nice to write the quadrant positions to the hdf5 file in `to_h5_file_and_quad_positions()` and at the same time make the `positions ` parameter of `from_h5_file_and_quad_positions()` optional if the positions exist in the file (while still allowing overwriting the quad positions in the file if they are passed explicitly).

**Comment by takluyver** [comment]
I've been thinking of something along those lines, but so far I've been reluctant to make a file format where sometimes you need quadrant positions separately and sometimes you don't. It's useful to know that someone wants this, therefore. :+1:

**Comment by takluyver** [comment]
I've had a go at this in #92.
