### ISSUE TITLE
ePix100 : wrong expected data shape

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/EXtra-geom#96]
[documentation](https://iopscience.iop.org/article/10.1088/1742-6596/493/1/012012) says ePix100 asic's Array size is 352x384, but the data we store has 2 extra rows.

**Comment by takluyver** [comment]
Is that related to this note in the docstring?

> There are 4 more rows in raw data. These are calibration pixels. They have the same electronics as normal pixels but aren't wired to the sensor. They are two first and two last rows in the raw data array. This class assumes that calibration rows are cut.

cc @egorsobolev

**Comment by egorsobolev** [comment]
Yes, it is. Our raw data contain these calibration rows.

**Comment by tmichela** [comment]
closed by #97
