### ISSUE TITLE
ePix : position modules

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/EXtra-geom#99]
An annoyance I encountered with ePix is that the data has 2 dimensions where other detectors have 3 (mod, ss, fs) but still expects you to feed data with 3 dimensions, so you have to add a dummy dimension in between the frame axis and the fs/ss axis.
I'd like to change the expected shape for this detector to accept 2d data.
That's a breaking change, but I believe this isn't used yet, so we could sneak that in 😏 

opinions @takluyver @egorsobolev ?

**Comment by takluyver** [comment]
For PNCCD, we treat it as two 512 x 1024 modules, but allow the data to be passed in as either (2, 512, 1024) or (1024, 1024), reshaping it automatically. We could easily do something similar for assembling a single frame of ePix data, adding the extra dimension if necessary.

It gets slightly more complicated for assembling multiple frames at once, but so long as it's a single module, the only ambiguity is whether a (1, 352, 384) input should make an output with an extra length 1 dimension (a stack of 1 frame) or not. I think I'd go for not, just in case anyone is already using this, but if we're sufficiently convinced that we control all the code that uses it, we could chnage that.

**Comment by tmichela** [comment]
thanks for the pointer, I'll try something like that.

**Comment by egorsobolev** [comment]
I would add that the set of ePix can be assembled in one big multi-module detector. 

There is also a question: what to do with our single module but two sensor detectors (which has two individually and independently located geometry fragments)?

**Comment by takluyver** [comment]
> I would add that the set of ePix can be assembled in one big multi-module detector.

Thanks, we should keep that in mind.

>  what to do with our single module but two sensor detectors (which has two individually and independently located geometry fragments)?

Is it just the gap between them that can vary? Or do we need an alternative constructor to allow the two pieces to be positioned fully independently? Or are they different enough that we should make separate classes? It looks like there aren't yet names for these two variants of ePix100.

(It's not entirely consistent, but the rough idea for EXtra-geom is that a 'module' is the unit which is read out together and stored in one HDF5 dataset, even if the tiles within it can be independently positioned)

**Comment by takluyver** [comment]
Ah, just read your comment on #97:

> In the second layout, it is not a pixel gap. Modules are assembled mechanically and can be located with a shift of columns and with a rotation, and not even in the same plane. I suppose 2nd layout requires multi-module geometry.

That implies we will need at least an alternative constructor (something like `from_sensor_positions`). It doesn't necessarily need to mean multi-module, because we give each tile a position.

**Comment by egorsobolev** [comment]
Forgot the details. Then alternative constructor is a better idea, indeed.

**Comment by tmichela** [comment]
> I would add that the set of ePix can be assembled in one big multi-module detector.

I'm not aware of any plans for that at EuXFEL, are you?

**Comment by egorsobolev** [comment]
I'm not also. But why not keep this option open?

**Comment by tmichela** [comment]
closed by #97
